[package]
name = "fasd"
version = "0.1.1"
edition = "2021"
publish = false
description = "Native zshrs plugin porting fasd file+directory frecency"
authors = ["MenkeTechnologies"]
repository = "https://github.com/MenkeTechnologies/zshrs-fasd"
homepage = "https://github.com/MenkeTechnologies/zshrs-fasd"

[lib]
name = "fasd"
crate-type = ["cdylib", "rlib"]

[dependencies]
znative = "0.12"
regex = "1"
